temp

diff --git a/ELK/makefile b/ELK/makefile
--- a/ELK/makefile
+++ b/ELK/makefile
@@ -1,30 +1,39 @@
 .PHONY: install start stop check apikey remove show
-kibanaip=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker-elk_kibana_1`
-esip=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker-elk_elasticsearch_1`
-elastic_version=8.2.0
-install: #downlaod & setting ELK
-	if test -d docker-elk;then make remove && rm -rf docker-elk;else echo "git";fi;
-	git clone https://github.com/deviantony/docker-elk.git
-	cd docker-elk &&\
-	sed -i "s/ELASTIC_VERSION=.\..\../ELASTIC_VERSION=$(elastic_version)/g" .env && \
-	docker-compose up -d &&\
-	sed -i "s/elasticsearch:9200/$(esip):9200/g" kibana/config/kibana.yml && \
-	echo server.publicBaseUrl: "http://$(kibanaip):5601" >> kibana/config/kibana.yml && \
+kibanaip=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' elk-kibana-1`
+esip=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' elk-es01-1`
+elastic_version=9.0.0
+elastic_password=`grep ELASTIC_PASSWORD .env | cut -d '=' -f2`
+
+install: #setup ELK with existing files
+	@echo "Setting up ELK stack..."
+	@sed -i '' "s/STACK_VERSION=.*/STACK_VERSION=$(elastic_version)/g" .env
+	@if ! docker network ls | grep -q elk; then \
+		docker network create elk; \
+	fi
 	docker-compose up -d
+	@echo "Waiting for services to initialize..."
+	@sleep 30
 	@make show
 	@make check
+
 show:
-	@echo kibana ip is $(kibanaip)
-	@echo es ip is $(esip)
+	@echo "Kibana IP: $(kibanaip)"
+	@echo "Elasticsearch IP: $(esip)"
+
 start:
-	cd docker-elk && docker-compose up -d
+	docker-compose up -d
+
 stop:
-	cd docker-elk && docker-compose down
+	docker-compose down
+
 check:
-	curl http://$(esip):9200 -u elastic:changeme
+	@echo "Checking Elasticsearch connection..."
+	@curl -s -k https://localhost:9200 -u elastic:$(elastic_password) || echo "Connection failed"
+
 apikey:
-	cd docker-elk && \
+	@echo "Generating Kibana encryption keys..."
 	docker-compose exec kibana bin/kibana-encryption-keys generate | tail -4 | tee kibana/config/kibana.yml 
-	docker restart docker-elk_kibana
+	docker restart elk-kibana-1
+
 remove:
-	cd docker-elk && docker-compose down -v
+	docker-compose down -v
